dataset_name: text_only
dataset_kwargs:
  token: False

task: "mathverse_testmini_text_only_val"
output_type: generate_until
doc_to_visual: !function utils.mathverse_doc_to_visual
doc_to_text: !function utils.mathverse_doc_to_text
doc_to_target: "answer"

process_results: !function utils.mathverse_process_results
metric_list:
  - metric: gpt_eval_score
    aggregation: !function utils.mathverse_aggregate_results_eval
    higher_is_better: true
  - metric: submission
    aggregation: !function utils.mathverse_aggregate_results_submission
    higher_is_better: true
  
lmms_eval_specific_kwargs:
  default:
    shot_type: "format-prompt" # can also be "custom-prompt"
    query_type: "query_wo" # now only support query_wo
model_specific_generation_kwargs:
  llava:
    image_aspect_ratio: original

include: _default_template_yaml